services:
  backend:
    build:
      context: ./backend
    container_name: snap-bucket-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      args:
        VITE_BACKEND_URL: http://localhost:5000
    container_name: snap-bucket-client
    ports:
      - "3000:80"
    depends_on:
      - backend
