services:
  - type: web
    name: grocery-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://ajamanjain27:Aman%4058816@cluster0.kj8xlxm.mongodb.net/grocery_db?retryWrites=true&w=majority
      - key: PORT
        value: 5000
